### ISSUE TITLE
MFOD attack is not working

### ISSUE THREAD

**Issue by nonokh** [f4rih/websploit#11]
after running the _wsf:MFOD>run_ command, nothing is happening and no new window is opening which shows the hosts connections.
This is where it get hangs.
![wsf](https://user-images.githubusercontent.com/31509565/38501246-24966e54-3c2a-11e8-8a51-d5aeb237a117.png)

**Comment by RedToor** [comment]
This module work with ettercap, it verify if is running background.

**Comment by JasimAlrawie** [comment]
you left the redhost empty 😗
