### ISSUE TITLE
print error.

### ISSUE THREAD

**Issue by kiraoftheweb** [f4rih/websploit#17]
File "/usr/bin/websploit", line 155
    print "Wrong Command => ", terminal
                            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Wrong Command => ", terminal)?

**Comment by sachinlobo11** [comment]
try with import __future__
Or from __future import printfunction (see doc) but it didnt work ...core module not available how to install?

**Comment by websploit** [comment]
new version released and all bugs fixed. check it out. thanks.

**Comment by hitchcliff** [comment]
I'm still facing this problem though. I'm using `python3.9.2`, any news on this?
