### ISSUE TITLE
why ami getting this error

### ISSUE THREAD

**Issue by lordcharlx** [f4rih/websploit#19]
![screenshot at 2019-02-23 11-05-29](https://user-images.githubusercontent.com/5570136/53284974-5dfe2880-375b-11e9-91bb-1839053c8e33.png)

**Comment by inajmi** [comment]
I am also getting the same error

**Comment by abdulriiyaz** [comment]
Pip2 install requests
Pip2 install scapy
Then run using python2
Or just update using wsf-update.py file and uograde the framework using upgrade command in wsf.
