### ISSUE TITLE
Websploit wouldn't start: ImportError: No module named scapy.all

### ISSUE THREAD

**Issue by drew1kun** [f4rih/websploit#2]
Installed, when running `sudo websploit` getting this:

```
Traceback (most recent call last):
  File "./websploit", line 55, in <module>
    from modules import arp_poisoner
  File "/Users/drewshg312/tmp/websploit/modules/arp_poisoner.py", line 11, in <module>
    from scapy.all import *
ImportError: No module named scapy.all
```

**Comment by RedToor** [comment]
is bacause scapy library not is installed, you can install with 
-- http://www.secdev.org/projects/scapy/doc/installation.html --
this framework is oriented to security distro's as kali or backtrack, this ditro's have all libraries necesary.

**Comment by drew1kun** [comment]
Thanx for pointing me to the right direciton. I'm using OSX Yosemite... installed `scapy` with `brew`. Now websploit starts, but getting this message:

```
WARNING: No route found for IPv6 destination :: (no default route?)
```

Any ideas?

**Comment by RedToor** [comment]
No problem, No is important. you can working now.

**Comment by drew1kun** [comment]
already got it! Thanx man!
