### ISSUE TITLE
Sniffing disable internet on device

### ISSUE THREAD

**Issue by Palmus84** [f4rih/websploit#20]
Every time I use Websploit (like every other mitm scripts) and I choose a target (smartphone, notebook), the target will lose internet connection. How should I fix it?

Kali Linux 4.19.0-kali3-amd64 (dual boot)
Wifi: Alfa AWUS036NHA and AWUS036NH

**Comment by websploit** [comment]
new version released and all bugs fixed. check it out. thanks.
