### ISSUE TITLE
Needs to be ported to Python 3

### ISSUE THREAD

**Issue by rhertzog** [f4rih/websploit#24]
Hello,

as per https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939260 we are getting rid of Python 2 in Debian and websploit is still Python 2 code. Its continued inclusion in Debian and Kali is thus subject to its update to Python 3.

Do you have plans to port it to Python 3 ?

Thank you for your work on websploit.

Raphaël, a Kali/Debian package maintainer.

**Comment by rhertzog** [comment]
FTR, the upstream author expressed interest on working towards Python 3 support in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939260#33

**Comment by websploit** [comment]
ported to python3, done
