### ISSUE TITLE
Can't use websploit. 😭😭😭 

### ISSUE THREAD

**Issue by jasmon93** [f4rih/websploit#27]
This what i got.

Traceback (most recent call last):
  File "websploit.py", line 3, in <module>
    from .core.utils import check_dependencies
ImportError: attempted relative import with no known parent package

**Comment by websploit** [comment]
Hi @jasmon93 
make sure you have latest version, currently is 4.0.3.
`git clone https://github.com/websploit/websploit.git`
run setup :
`python3 setup.py install`
then open new terminal and type:
`websploit`
if there is issue let me know.
Thanks.

**Comment by jasmon93** [comment]
Hi sir. Thank you for your reply. Im really happy but let me try first.
Anything i'll ping you sir. 🙏🏻

**Comment by jasmon93** [comment]
Hi sir. Failed again. I dont know if my termux got the problem or not. But.
Its keep like this. Same error. 😭

**Comment by websploit** [comment]
It works on debian and Mac OSX  perfectly. What are your OS and version of Python ?

**Comment by jasmon93** [comment]
I think maybe because i'm using at termux. Thats why i cannot use.

**Comment by PandaFoss** [comment]
First of all you must install Python:

`$ apt install python`

Then install the dependencies:

`$ pip install scapy`

`$ pip install requests`

Clone the repository and enter:

`$ git clone https://github.com/websploit/websploit.git`

`$ cd websploit`

You must use `setup.py` to build and install it:

`$ python setup.py build`

`$ python setup.py install`

Now you must log in as superuser and execute it as follows:

`$ su`

`# ../../usr/bin/websploit`

Ready!

**Comment by jasmon93** [comment]
Ok thank you sir

**Comment by chiya369** [comment]
thank you
