### ISSUE TITLE
set mon wlan1 not working

### ISSUE THREAD

**Issue by muhackl** [f4rih/websploit#3]
Some chipsets generate "wlan0" or "wlan1" instead of "mon0" or "mon1" when setting the interface to monitor mode. If I try to change mon to wlan1 in websploit, it just sets it to "wlan". The number 1 always misses. It seems the set mon command does not accept more characters then 4.

**Comment by RedToor** [comment]
I understand i look https://github.com/websploit/websploit/blob/master/modules/wifi_honeypot.py#L43 
Line Code 43 : 

```
        elif com[0:7] == 'set mon':
            options[5] = com[8:12]
            print "MON => ", options[5]
            wifi_honeypot()
```

the script Just save `options[5] = com[8:12]` 4 Characters (8+4=12)

Soluction: Edit the line with `options[5] = com[8:]` so

```
        elif com[0:7] == 'set mon':
            options[5] = com[8:]
            print "MON => ", options[5]
            wifi_honeypot()
```
