### ISSUE TITLE
wifi jammer dosen't work if essid contains spaces

### ISSUE THREAD

**Issue by surapuramakhil** [f4rih/websploit#5]
need to change code in wifi_jammer.py

**Comment by RedToor** [comment]
you can edit https://github.com/websploit/websploit/blob/master/modules/wifi_jammer.py#L70 by

`xterm_3 = "xterm -e airodump-ng -c " + options[4] + " --bssid \"" + options[1] + "\" \"" + options[3] + "\" &"`

and https://github.com/websploit/websploit/blob/master/modules/wifi_jammer.py#L73 by 

` xterm_4 = "xterm -e aireplay-ng --deauth 9999999999999 -o 1 -a \"" + options[1] + "\" -e \"" + options[2] + "\" " + options[3] + " &"
`

just add ` \" `
