### ISSUE TITLE
Error to run in kali linux 2016.2

### ISSUE THREAD

**Issue by ghost** [f4rih/websploit#8]
root@AVI:~# websploit
Traceback (most recent call last):
  File "/usr/bin/websploit", line 37, in <module>
    from core import wcolors
ImportError: cannot import name wcolors

**Comment by 4shadoww** [comment]
Websploit is obsolete and dead. You should use instead [Hakku Framework](https://github.com/4shadoww/hakkuframework) or [Katana Framework](https://github.com/PowerScript/KatanaFramework).
