### ISSUE TITLE
i get error mscli not found

### ISSUE THREAD

**Issue by christmex** [f4rih/websploit#9]
i get this error 

wsf:Browser_Autopwn > run
[*]Starting WebServer ... Please Wait ...
[*]Configuration DNS Spoof ... 
[*]Creating Infected Page For Victim ...
[*]Engine Has Been Started.
sh: 1: msfcli: not found
wsf > 

====================================
please help how to repair it

**Comment by RedToor** [comment]
Metasploit is required.

**Comment by dcliss** [comment]
using kali linux still not working . i saw the msfcli is depreceated any help mate
